### ISSUE TITLE
Unable to use ntfy command in SSH

### ISSUE THREAD

**Issue by link-leocorde** [YunoHost-Apps/ntfy_ynh#7] opened 2023-01-22 03:53 UTC
### Describe the bug
Unable to use `ntfy` command per [documentation](https://docs.ntfy.sh/config/#users-and-roles). Therefore unable to add users or control access to topics by updating the `user.db` with the `ntfy` command.
### Context
- Hardware: *Raspberry Pi 3*
- YunoHost version: 11.0.10.2
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: *1.30.1~ynh1*
### Steps to reproduce
```sh
ntfy user list
```
```
ntfy access USERNAME TOPIC PERMISSION
```
### Expected behavior
List of users or define access for a topic.
### Logs
Just returns `-bash: ntfy: command not found`

**Comment by tituspijean** [comment] 2023-01-22 08:23
Try:

```
sudo su
cd /var/www/ntfy
sudo -u ntfy bash
#and then your commands
```

The issue is that apps are not globally accessible, you need to go to their directory and run their binaries as the app's user.

**Comment by link-leocorde** [comment] 2023-01-22 17:06
```
root@sgc:~# sudo su
root@sgc:~# cd /var/www/ntfy
root@sgc:/var/www/ntfy# sudo -u ntfy bash
ntfy@sgc:~$ ntfy user list
bash: ntfy: command not found
```
Doesn't appear to have worked.

**Comment by l-x** [comment] 2023-02-15 16:36
`ntfy users list` assumes that the binary can be found in `PATH` and the config file is located under `/etc/ntfy/server.yml`.

Both does **not** apply to a installation of ntfy_ynh.

Given your app id is `ntfy` (which is the case in most installations) the binary and config file will be in `/var/www/ntfy`. To list the users you will have to call something like this:

```sh
sudo -su
cd /var/www/ntfy
./ntfy user -c server.yml list
```
or without `cd` and in one line:

```sh
$ APP_PATH=/var/www/ntfy sudo $APP_PATH/ntfy user -c $APP_PATH/server.yml list
```

to list the users.

tagging @link-leocorde

**Comment by l-x** [comment] 2023-02-15 16:38
Maybe we should improve the documentation to point this out. Or deploy some sort of script.

**Comment by link-leocorde** [comment] 2023-02-16 03:26
This appears to work. Is there a way to short-hand this so I can just use the `ntfy` command without all the other stuff first?

**Comment by l-x** [comment] 2023-02-16 07:57
The most simple solution for you should be to create a file `ntfy_server` in your everyday users home directory with the following contents:

```sh
#!/bin/sh

CMD=$1
shift

sudo -Hu ntfy sh -c "\$HOME/ntfy $CMD -c \$HOME/server.yml $@"
```
and make it executable:
```sh
chmod +x ~/ntfy_server
```

After that you can call this script like so
```sh
~/ntfy_server user list
```

But be aware: This script will only work for the server commands `serve` (which does not make sense), `user` and `access`.

**Closed** 2023-02-20 15:13 UTC
Labels: question
